from models import DataManager
import tkinter as tk
from tkinter import ttk, filedialog
from typing import Type
import pandas as pd

class HomeFrame(ttk.Frame):
    def __init__(self, parent):
        super().__init__(parent)

        disclaimer_frame = ttk.Frame(self, borderwidth=2, relief='ridge')
        disclaimer_lbl = ttk.Label(disclaimer_frame, text='DISCLAIMER', font=('Arial', 20, "bold"))
        msg_block_1 = tk.Message(disclaimer_frame, width=600, text="        This tool has been developed to compile Taiga task data and GitHub commit data to generate reports. While efforts have been made to ensure the tool functions as intended, it is provided as is without any guarantees or warranties, express or implied.")
        user_responsibilities_lbl = ttk.Label(disclaimer_frame, text='User Responsibility', font=('Arial', 13, "bold"))
        msg_block_2 = tk.Message(disclaimer_frame, width=600, text="        Users are solely responsible for reviewing, verifying, and validating the accuracy and completeness of the reports generated by this tool. The developer makes no representations regarding the reliability or suitability of the tool’s outputs for any particular use.")
        liability_lbl = ttk.Label(disclaimer_frame, text='Liability', font=('Arial', 13, "bold"))
        msg_block_3 = tk.Message(disclaimer_frame, width=600, text="        By using this tool, users acknowledge that the developer is not liable for any errors, omissions, misinterpretations, or consequences resulting from reliance on the tool’s outputs. The developer assumes no responsibility for any decisions, actions, or outcomes based on the use of this tool or the use of any reports generated by the tool.")
        acknowledgement_msg = tk.Message(disclaimer_frame, width=600, font=('Arial', 16, "bold"), text="By continuing to use this tool, you agree to these terms.")

        disclaimer_lbl.pack()
        msg_block_1.pack(anchor='w')
        user_responsibilities_lbl.pack(fill='x', anchor='w', padx=4)
        msg_block_2.pack(anchor='w')
        liability_lbl.pack(fill='x', anchor='w', padx=4)
        msg_block_3.pack(anchor='w', pady=(0, 5))
        acknowledgement_msg.pack(anchor='w')

        disclaimer_frame.pack()