from models import DataManager
import tkinter as tk
from tkinter import ttk, filedialog
from typing import Type
import pandas as pd

class HomeFrame(ttk.Frame):
    def __init__(self, parent):
        super().__init__(parent)

        disclaimer_frame = ttk.Frame(self, borderwidth=2, relief='ridge')
        disclaimer_lbl = ttk.Label(disclaimer_frame, text='DISCLAIMER', font=('Arial', 20, "bold"))
        msg_block_1 = tk.Message(disclaimer_frame, width=600, text="        This tool has been developed to compile Taiga task data and GitHub commit data to generate reports. While efforts have been made to ensure the tool functions as intended, it is provided as is without any guarantees or warranties, express or implied.")
        user_responsibilities_lbl = ttk.Label(disclaimer_frame, text='User Responsibility', font=('Arial', 13, "bold"))
        msg_block_2 = tk.Message(disclaimer_frame, width=600, text="        Users are solely responsible for reviewing, verifying, and validating the accuracy and completeness of the reports generated by this tool. The developer makes no representations regarding the reliability or suitability of the tool’s outputs for any particular use.")
        liability_lbl = ttk.Label(disclaimer_frame, text='Liability', font=('Arial', 13, "bold"))
        msg_block_3 = tk.Message(disclaimer_frame, width=600, text="        By using this tool, users acknowledge that the developer is not liable for any errors, omissions, misinterpretations, or consequences resulting from reliance on the tool’s outputs. The developer assumes no responsibility for any decisions, actions, or outcomes based on the use of this tool or the use of any reports generated by the tool.")
        acknowledgement_msg = tk.Message(disclaimer_frame, width=600, font=('Arial', 16, "bold"), text="By continuing to use this tool, you agree to these terms.")

        disclaimer_lbl.pack()
        msg_block_1.pack(anchor='w')
        user_responsibilities_lbl.pack(fill='x', anchor='w', padx=4)
        msg_block_2.pack(anchor='w')
        liability_lbl.pack(fill='x', anchor='w', padx=4)
        msg_block_3.pack(anchor='w', pady=(0, 5))
        acknowledgement_msg.pack(anchor='w')

        how_to_use_frame = ttk.Frame(self, borderwidth=2, relief='ridge')
        how_to_use_lbl = ttk.Label(how_to_use_frame, text='How To Use', font=('Arial', 20, "bold"))
        tabControl = ttk.Notebook(how_to_use_frame)
        
        taiga_use_frame = ttk.Frame(tabControl)
        taiga_use_lbl = ttk.Label(taiga_use_frame, text='Taiga Tab', font=('Arial', 13, "bold"))
        taiga_txt = "On the Taiga tab, users can import data by file or by using the Taiga api:"
        taiga_txt += "\n        1.) Importing by files ('From File' tab): After downloading the User Story and Task csv files from the 'Reports' page in the Taiga project's settings, the user can select the filepath to these two files and then import the Taiga data and display it in the tab."
        taiga_txt += "\n        2.) Importing by API ('From API' tab): The user can find the api urls for retrieving the User Story and Task csv data from the same 'Reports' page in the Taiga project settings. Then the user can enter these within the application and import the Taiga data and display it in the tab."
        taiga_txt += "\n\nOnce the data is imported the user can modify the data as they need to (disclaimer: The application isn't designed to handle non-typical data formats for these fields, so be careful about what is entered when editting the data). Be sure to hit the 'Save Current Table' button when you want to keep the current data, otherwise, you will lose any changes you have made."
        taiga_use_block = tk.Message(taiga_use_frame, width=600, text=taiga_txt)
        taiga_use_lbl.pack()
        taiga_use_block.pack()

        gh_use_frame = ttk.Frame(tabControl)
        gh_use_lbl = ttk.Label(gh_use_frame, text='GitHub Tab', font=('Arial', 13, "bold"))
        gh_txt = "On the GitHub tab, users can import data by using the GitHub API:"
        gh_txt += "\n       - Note: You will need to generate a token that will be used by the application to make GitHub API calls, this can be done on GitHub."
        gh_txt += "\n       - The user will need to specify their GitHub username, the GitHub access token (classic token is what was used for testing), the repository owner's username, and the repositories name."
        gh_txt += "\n       - Once all of this information is entered, the user can then import the commit data from this repository to display in the tab."
        gh_txt += "\n\nOnce the data is imported the user can modify the data as they need to (disclaimer: The application isn't designed to handle non-typical data formats for these fields, so be careful about what is entered when editting the data). Be sure to hit the 'Save Current Table' button when you want to keep the current data, otherwise, you will lose any changes you have made."
        gh_use_block = tk.Message(gh_use_frame, width=600, text=gh_txt)
        gh_use_lbl.pack()
        gh_use_block.pack()

        reports_use_frame = ttk.Frame(tabControl)
        reports_use_lbl = ttk.Label(reports_use_frame, text='Reports Tab', font=('Arial', 13, "bold"))
        reports_txt = "On the Reports tab, users can generate various reports based on the imported Taiga and GitHub data:"
        reports_txt += "\n      - General/Master Taiga Data Reports: Effectively the same as what is within the Taiga tab"
        reports_txt += "\n      - General/Master GitHub Data Reports: Effectively the same as what is within the GitHub tab"
        reports_txt += "\n      - Work Summary Reports"
        reports_txt += "\n      - Individual Contribution Reports: This will generate a report in a similar format to the IC reports that are submitted every two weeks"
        reports_txt += "\n\n**Note: The Work Summary Reports and the Individual Contribution Reports do output the Task and Github link columns with actual hyperlinks. However, they are generated by inserting a formula into the spreadsheet, which is prohibited in the official report submissions."
        reports_txt += " To get around this, you can take these columns of data, paste them into a word document and then copy them over to the work summary or IC template spreadsheets (and reformat the text/font to match typical hyperlink format)."
        reports_use_block = tk.Message(reports_use_frame, width=600, text=reports_txt)
        reports_use_lbl.pack()
        reports_use_block.pack()

        tabControl.add(taiga_use_frame, text='Taiga Tab')
        tabControl.add(gh_use_frame, text='GitHub Tab')
        tabControl.add(reports_use_frame, text='Reports Tab')
        
        how_to_use_lbl.pack()
        tabControl.pack(expand = 1, fill ="both") 
    
        disclaimer_frame.pack()
        how_to_use_frame.pack()